### ISSUE TITLE
Dimensions is not firing window/screen size-changed events

### ISSUE THREAD

**Issue by jaredhms** [microsoft/react-native-windows#3407]
It looks like DeviceInfo/DeviceInfoModule only grabs the dimensions up-front, doesn't subscribe to Xaml updates, and doesn't fire the events to ReactNative.  This makes it difficult for our app to respond to window resizing.

**Comment by jrdnlx** [comment]
Hey, I might be interested in attempting this, can you provide any more details?

**Comment by chrisglein** [comment]
@jaredhms Looks like we may have someone willing to help contribute and fix this (thanks @jrdnlx!). 
Have you looked into the device info community module (https://github.com/react-native-community/react-native-device-info)?

@kmelmon I know you were staring to look into that module to see where was the best place to get this info. Want to weigh in? Is this an example where functionality has migrated outside of lean core?

**Comment by kmelmon** [comment]
> @jaredhms Looks like we may have someone willing to help contribute and fix this (thanks @jrdnlx!).
> Have you looked into the device info community module (https://github.com/react-native-community/react-native-device-info)?
> 
> @kmelmon I know you were staring to look into that module to see where was the best place to get this info. Want to weigh in? Is this an example where functionality has migrated outside of lean core?

I haven't looked at the community module, but I have been debugging through the Android implementation.  The code that deals with window size/screen size/scale is all part of lean core.

**Comment by kmelmon** [comment]
Looking again at this...  What version of react-native-windows are you using?  I've been debugging a related issue and noticed the vnext version does correctly fire Dimensions updates when the window change sizes, so I'm puzzled as to why this is apparently not working for you.

**Comment by kmelmon** [comment]
@ddalp I believe you did a fix in this area recently.  Is it possible you fixed this already?

**Comment by jaredhms** [comment]
@kmelmon / @chrisglein -- @namrog84 told me that this was fixed in the last release, but I haven't gotten a chance to confirm yet.

**Comment by kmelmon** [comment]
Thanks for the update!  I can confirm it's working so it's safe to close this.

**Comment by stmoy** [comment]
It looks like the react-native-responsive-screen module still doesn't work as expected, and it seems to be related to this bug. Reopening.

https://github.com/microsoft/react-native-windows/issues/3407

**Comment by kmelmon** [comment]
I tracked this back to a regression from Di's fix, which was working.  Filed a separate issue #6269 to track fixing the regression.
