### ISSUE TITLE
SampleModuleCPP should behave the same way when it is called from both SampleAppCPP and SmapleAppCS

### ISSUE THREAD

**Issue by enm10k** [microsoft/react-native-windows#3594]
### Environment

```
C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>react-native -v
react-native-cli: 2.0.1
react-native: 0.60.0-microsoft.15

C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>npm ls rnpm-plugin-windows
microsoft-reactnative-sampleapps@0.0.1 C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps
`-- rnpm-plugin-windows@0.3.7  -> C:\Users\enm10k\react-native-windows\node_modules\rnpm-plugin-windows


C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>node -v
v12.9.0

C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>npm -v
6.10.2

C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>yarn --version
1.17.3

```

- Target Platform Version(s): 10.0.18362.0
- Target Device(s): Desktop
- Visual Studio Version: Visual Studio 2019
- Build Configuration: Debug

### Steps to Reproduce

1. `yarn install & yarn build`
2. Build `C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps\windows\SampleApp.sln`

### Expected Behavior

SampleModuleCPP should behave the same way when it is called from both SampleAppCPP and SmapleAppCS.

### Actual Behavior

Call SampleModuleCPP from SampleAppCPP

```
SampleApp._onPressHandlerSMCPP()
SampleModuleCPP.NumberConstant: 3.141592653589793
SampleModuleCPP.StringConstant: Hello World
SampleModuleCPP.VoidMethod()
SampleModuleCPP.VoidMethodWithArgs(42.000000)
SampleModuleCPP.ReturnMethod()
SampleModuleCPP.ReturnMethodWithArgs(42.000000)
SampleModuleCPP.ExplicitCallbackMethod()
SampleModuleCPP.ExplicitCallbackMethodWithArgs(42.000000)
SampleModuleCPP.ExplicitPromiseMethod()
SampleModuleCPP.ExplicitPromiseMethodWithArgs(42.000000)
SampleModuleCPP.ReturnMethod => 3.141592653589793
SampleModuleCPP.ReturnMethodWithArgs => 3.141592653589793
SampleModuleCPP.ExplicitCallbackMethod => 3.141592653589793
SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.141592653589793
SampleModuleCPP.ExplicitPromiseMethod then => 3.141592653589793
SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.141592653589793
```

Call SampleModuleCPP from SampleAppCS

```
SampleApp._onPressHandlerSMCPP()
SampleModuleCPP.NumberConstant: 3.141592653589793
SampleModuleCPP.StringConstant: Hello World
SampleModuleCPP.ReturnMethod => 3.141592653589793
SampleModuleCPP.ReturnMethodWithArgs => 3.141592653589793
SampleModuleCPP.ExplicitCallbackMethod => 3.141592653589793
SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.141592653589793
SampleModuleCPP.ExplicitPromiseMethod then => 3.141592653589793
SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.141592653589793
```

### Additional context

I ran into the issue with the latest master.

```
C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>git log -1
commit 8b8798862bc8e051b294aa9ef6eb51e840e22041 (HEAD -> master, tag: react-native-windows_v0.60.0-vnext.61, tag: react-native-windows-extended_v0.60.15, origin/master, origin/HEAD)
Author: React-Native-Windows Bot <53619745+rnbot@users.noreply.github.com>
Date:   Fri Nov 1 23:40:12 2019 +0000

    applying package updates ***NO_CI***
```

**Comment by jonthysell** [comment]
I'm not seeing it:

> SampleAppCS:
> 
> SampleApp.onPressSampleModuleCPP()
> SampleModuleCPP.NumberConstant: 3.14159
> SampleModuleCPP.StringConstant: Hello World
> SampleModuleCPP.NumberConstantViaProvider: 3.14159
> SampleModuleCPP.StringConstantViaProvider: Hello World
> SampleModuleCPP.VoidMethod()
> SampleModuleCPP.VoidMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod()
> SampleModuleCPP.ReturnMethodWithArgs(42.000000)
> SampleModuleCPP.ExplicitCallbackMethod()
> SampleModuleCPP.ExplicitCallbackMethodWithArgs(42.000000)
> SampleModuleCPP.ExplicitPromiseMethod()
> SampleModuleCPP.ExplicitPromiseMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod => 3.14159
> SampleModuleCPP.ReturnMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitCallbackMethod => 3.14159
> SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitPromiseMethod then => 3.14159
> SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.14159
> 
> SampleAppCPP:
> 
> SampleApp.onPressSampleModuleCPP()
> SampleModuleCPP.NumberConstant: 3.14159
> SampleModuleCPP.StringConstant: Hello World
> SampleModuleCPP.NumberConstantViaProvider: 3.14159
> SampleModuleCPP.StringConstantViaProvider: Hello World
> SampleModuleCPP.VoidMethod()
> SampleModuleCPP.VoidMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod()
> SampleModuleCPP.ReturnMethodWithArgs(42.000000)
> SampleModuleCPP.ExplicitCallbackMethod()
> SampleModuleCPP.ExplicitCallbackMethodWithArgs(42.000000)
> SampleModuleCPP.ExplicitPromiseMethod()
> SampleModuleCPP.ExplicitPromiseMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod => 3.14159
> SampleModuleCPP.ReturnMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitCallbackMethod => 3.14159
> SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitPromiseMethod then => 3.14159
> SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.14159

Two possibilities:
1. I've fixed it in the PR that's currently out, #3561, which has a lot of updates to the SampleApps
2. All of these calls are async - it's possible to see them out of order, or for the otuput to be interrupted by other debug logging.

**Comment by chrisglein** [comment]
@enm10k Can you validate with Jon's latest here to see if this still repros?
Also there's no guarantees about the ordering of the async events so keep that in mind.

**Comment by enm10k** [comment]
Thanks for replying.

> I've fixed it in the PR that's currently out, #3561, which has a lot of updates to the SampleApps

I updated my environment but I'm still getting the same issue.
I tested with the following version.

```
C:\Users\enm10k\react-native-windows\packages\microsoft-reactnative-sampleapps>git log -1
commit 411543b06bd4d0b15822423b9051c2c0319b67b6 (HEAD -> master, tag: react-native-windows_v0.60.0-vnext.67, origin/master, origin/HEAD)
Author: React-Native-Windows Bot <53619745+rnbot@users.noreply.github.com>
Date:   Fri Nov 8 00:30:50 2019 +0000

    applying package updates ***NO_CI***

```

> All of these calls are async - it's possible to see them out of order, or for the output to be interrupted by other debug logging.

This is the latest debug output I got.
I tested several times but I got a similar result every time.

It looks like debug messages of functions without return value are not displayed.
In my environment, it reproduces only in SampleAppCS.

```
SampleModuleCPP.TimedEventCPP() => 1
SampleModuleCS.TimedEventCS() => 1
SampleApp.onPressSampleModuleCPP()
SampleModuleCPP.NumberConstant: 3.14159
SampleModuleCPP.StringConstant: Hello World
SampleModuleCPP.NumberConstantViaProvider: 3.14159
SampleModuleCPP.StringConstantViaProvider: Hello World
SampleModuleCPP.ReturnMethod => 3.14159
SampleModuleCPP.ReturnMethodWithArgs => 3.14159
SampleModuleCPP.ExplicitCallbackMethod => 3.14159
SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.14159
SampleModuleCPP.ExplicitPromiseMethod then => 3.14159
SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.14159
SampleModuleCPP.TimedEventCPP() => 2
SampleModuleCS.TimedEventCS() => 2
SampleModuleCPP.TimedEventCPP() => 3
SampleModuleCS.TimedEventCS() => 3
SampleModuleCPP.TimedEventCPP() => 4
SampleModuleCS.TimedEventCS() => 4
SampleModuleCPP.TimedEventCPP() => 5
SampleModuleCS.TimedEventCS() => 5
SampleModuleCPP.TimedEventCPP() => 6
SampleModuleCS.TimedEventCS() => 6
スレッド 0x48bc はコード 0 (0x0) で終了しました。
SampleModuleCPP.TimedEventCPP() => 7
SampleModuleCS.TimedEventCS() => 7
SampleModuleCPP.TimedEventCPP() => 8
SampleModuleCS.TimedEventCS() => 8
SampleModuleCPP.TimedEventCPP() => 9
SampleModuleCS.TimedEventCS() => 9
SampleModuleCPP.TimedEventCPP() => 10
SampleModuleCS.TimedEventCS() => 10
SampleModuleCPP.TimedEventCPP() => 11
SampleModuleCS.TimedEventCS() => 11
SampleModuleCPP.TimedEventCPP() => 12
SampleModuleCS.TimedEventCS() => 12
SampleModuleCPP.TimedEventCPP() => 13
SampleModuleCS.TimedEventCS() => 13
SampleModuleCPP.TimedEventCPP() => 14
SampleModuleCS.TimedEventCS() => 14
SampleModuleCPP.TimedEventCPP() => 15
SampleModuleCS.TimedEventCS() => 15
SampleModuleCPP.TimedEventCPP() => 16
SampleModuleCS.TimedEventCS() => 16
SampleModuleCPP.TimedEventCPP() => 17
SampleModuleCS.TimedEventCS() => 17
SampleModuleCPP.TimedEventCPP() => 18
SampleModuleCS.TimedEventCS() => 18
SampleModuleCPP.TimedEventCPP() => 19
SampleModuleCS.TimedEventCS() => 19
SampleModuleCPP.TimedEventCPP() => 20
SampleModuleCS.TimedEventCS() => 20
SampleModuleCPP.TimedEventCPP() => 21
SampleModuleCS.TimedEventCS() => 21
...
```

**Comment by jonthysell** [comment]
I've set up a brand new machine and this still doesn't repro. Closing.


> $ react-native -v
> react-native-cli: 2.0.1
> react-native: 0.60.0-microsoft.16
> 
> $ npm ls rnpm-plugin-windows
> microsoft-reactnative-sampleapps@0.0.1 C:\code\rnw\packages\microsoft-reactnative-sampleapps
> `-- rnpm-plugin-windows@0.3.8  -> C:\code\rnw\node_modules\rnpm-plugin-windows
> 
> 
> $ node -v
> v10.16.3
> 
> $ npm -v
> 6.9.0
> 
> $ yarn --version
> 1.17.3

> cs app / cs lib
> 
> SampleApp.onPressSampleModuleCS()
> SampleModuleCS.NumberConstant: 3.14159
> SampleModuleCS.StringConstant: Hello World
> SampleModuleCS.NumberConstantViaProvider: 3.14159
> SampleModuleCS.StringConstantViaProvider: Hello World
> SampleModuleCS.VoidMethod()
> SampleModuleCS.VoidMethodWithArgs(42)
> SampleModuleCS.ReturnMethod()
> SampleModuleCS.ReturnMethodWithArgs(42)
> SampleModuleCS.ExplicitCallbackMethod()
> SampleModuleCS.ExplicitCallbackMethodWithArgs(42)
> SampleModuleCS.ExplicitPromiseMethod()
> SampleModuleCS.ExplicitPromiseMethodWithArgs(42)
> SampleModuleCS.ReturnMethod => 3.14159
> SampleModuleCS.ReturnMethodWithArgs => 3.14159
> SampleModuleCS.ExplicitCallbackMethod => 3.14159
> SampleModuleCS.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCS.ExplicitPromiseMethod then => 3.14159
> SampleModuleCS.ExplicitPromiseMethodWithArgs then => 3.14159
> 
> cs app / cpp lib
> SampleApp.onPressSampleModuleCPP()
> SampleModuleCPP.NumberConstant: 3.14159
> SampleModuleCPP.StringConstant: Hello World
> SampleModuleCPP.NumberConstantViaProvider: 3.14159
> SampleModuleCPP.StringConstantViaProvider: Hello World
> SampleModuleCPP::VoidMethod()
> SampleModuleCPP::VoidMethodWithArgs(42.000000)
> SampleModuleCPP::ReturnMethod()
> SampleModuleCPP::ReturnMethodWithArgs(42.000000)
> SampleModuleCPP::ExplicitCallbackMethod()
> SampleModuleCPP::ExplicitCallbackMethodWithArgs(42.000000)
> SampleModuleCPP::ExplicitPromiseMethod()
> SampleModuleCPP::ExplicitPromiseMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod => 3.14159
> SampleModuleCPP.ReturnMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitCallbackMethod => 3.14159
> SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitPromiseMethod then => 3.14159
> SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.14159
> 
> cpp app / cs lib
> SampleApp.onPressSampleModuleCS()
> SampleModuleCS.NumberConstant: 3.14159
> SampleModuleCS.StringConstant: Hello World
> SampleModuleCS.NumberConstantViaProvider: 3.14159
> SampleModuleCS.StringConstantViaProvider: Hello World
> SampleModuleCS.VoidMethod()
> SampleModuleCS.VoidMethodWithArgs(42)
> SampleModuleCS.ReturnMethod()
> SampleModuleCS.ReturnMethodWithArgs(42)
> SampleModuleCS.ExplicitCallbackMethod()
> SampleModuleCS.ExplicitCallbackMethodWithArgs(42)
> SampleModuleCS.ExplicitPromiseMethod()
> SampleModuleCS.ExplicitPromiseMethodWithArgs(42)
> SampleModuleCS.ReturnMethod => 3.14159
> SampleModuleCS.ReturnMethodWithArgs => 3.14159
> SampleModuleCS.ExplicitCallbackMethod => 3.14159
> SampleModuleCS.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCS.ExplicitPromiseMethod then => 3.14159
> SampleModuleCS.ExplicitPromiseMethodWithArgs then => 3.14159
> 
> cpp app / cpp lib
> SampleApp.onPressSampleModuleCPP()
> SampleModuleCPP.NumberConstant: 3.14159
> SampleModuleCPP.StringConstant: Hello World
> SampleModuleCPP.NumberConstantViaProvider: 3.14159
> SampleModuleCPP.StringConstantViaProvider: Hello World
> SampleModuleCPP::VoidMethod()
> SampleModuleCPP::VoidMethodWithArgs(42.000000)
> SampleModuleCPP::ReturnMethod()
> SampleModuleCPP::ReturnMethodWithArgs(42.000000)
> SampleModuleCPP::ExplicitCallbackMethod()
> SampleModuleCPP::ExplicitCallbackMethodWithArgs(42.000000)
> SampleModuleCPP::ExplicitPromiseMethod()
> SampleModuleCPP::ExplicitPromiseMethodWithArgs(42.000000)
> SampleModuleCPP.ReturnMethod => 3.14159
> SampleModuleCPP.ReturnMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitCallbackMethod => 3.14159
> SampleModuleCPP.ExplicitCallbackMethodWithArgs => 3.14159
> SampleModuleCPP.ExplicitPromiseMethod then => 3.14159
> SampleModuleCPP.ExplicitPromiseMethodWithArgs then => 3.14159
