### ISSUE TITLE
When selection is enabled, onPress handlers on Text components do not work

### ISSUE THREAD

**Issue by rigdern** [Microsoft/react-native-windows#564]
For example, in the following, `_handlePress` will never be called:

```
<Text selectable={true} onPress={this._handlePress}>
  Press me
</Text>
```

The problem is that when you are hovering over and interacting with the pressable text, the mouse cursor is in selection mode. It tries to select the text rather than firing tap, click, etc. events. I have a few ideas for how to solve this but none are ideal so far:
1. Manually do hit testing on `Text` to see if a pressable region was hit. To do this, we'd have to sign up for the `RichTextBlock's` pointer events using `AddHandler` so we can pass `true` for the `handledEventsToo` parameter. A major limitation is apparently we are stuck with the I-beam selection cursor when hovering over text. When trying to set it to something else like an arrow in the `PointerMoved` handler, the cursor rapidly flickers between I-beam and arrow. To fix this, we'd likely need a feature from the XAML team. Another concern is around the performance of the code that would do the hit testing.
2. Every nested Text component with an onPress handler is rendered as a [`Hyperlink`](https://msdn.microsoft.com/library/windows/apps/dn279356). This solution has some issues due to [limitations](https://msdn.microsoft.com/library/windows/apps/dn279356#hyperlink_limitations) with `Hyperlink`:
   - The major limitation with this approach is that [I don't think you can customize the hover color of the text](http://stackoverflow.com/questions/36517637/changing-hover-color-of-hyperlink).
   - You can only nest `Runs` and non-`Hyperlink` `Spans` inside of the `Hyperlink` (e.g. can't nest inline views). I suspect this won't be problematic in practice.
3. Every nested Text component with an onPress handler is rendered as an inline view. The issue with this approach is that when your selection includes the inline view, the copy command doesn't work.

**Comment by rozele** [comment]
Was this resolved with https://github.com/ReactWindows/react-native-windows/commit/a766d1a9ee4eb10199430b947de28fc9df2dff85?

**Comment by rigdern** [comment]
No, a766d1a9ee4eb10199430b947de28fc9df2dff85 doesn't fix this nor was it intended to fix this. I'm not sure of the right way to fix this bug yet.

**Comment by rigdern** [comment]
I'm thinking we should fix this by translating a `<Text>` with an `onPress` handler to a XAML `Hypelink`. There will be a lot of limitations in styling but a hyperlink scenario is probably the most common use of `onPress` on `Text` nodes anyway. Also, I can't think of a more general way to solve this nicely given the APIs XAML exposes.

**Comment by mrousal** [comment]
potential fix for this:
#1646

**Comment by rigdern** [comment]
@mrousal's fix improved the situation described by this bug but some stuff still isn't fixed. His fix only addressed putting `onPress` handlers on the outer most `Text` component. I suspect my description wasn't clear enough. I opened a new bug to track the remaining issues (#1679). I'll leave this bug closed.
