### ISSUE TITLE
Hovering a link in an AdaptiveCard crashes app with RNfW 0.66

### ISSUE THREAD

**Issue by jeanmaried** [microsoft/react-native-windows#9560]
### Problem Description

Hovering over an inline link in an AdaptiveCard is crashing app after upgrading to RN 0.66. I have a included two sample repos:

1. a regular UWP app using a AdaptiveCard (2.7.3) and AdaptiveCards.Rendering.Uwp (2.7.0) showing expected  behavior: https://github.com/jeanmaried/AdaptiveCard-UWP/tree/master

2. a RN 0.66 app with same nuget dependencies: https://github.com/jeanmaried/AdaptiveCard-RN
![crash](https://user-images.githubusercontent.com/28982554/154342704-8f1507fa-a1f7-4ece-9382-b879f0ffe432.PNG)

### Steps To Reproduce

1. Run AdaptiveCard-RN app.
2. Hover over "hover me" link.
3. App crashes due to unhandle errror

### Expected Results

Link should have expected hover behavior and not crash app.

### CLI version

npx react-native --version

### Environment

```markdown
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 1.43 GB / 15.69 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.17134.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32106.194 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.0 => 0.66.0
    react-native-windows: 0.66.11 => 0.66.11
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.16299

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

1. a regular UWP app using a AdaptiveCard (2.7.3) and AdaptiveCards.Rendering.Uwp (2.7.0) showing expected  behavior: https://github.com/jeanmaried/AdaptiveCard-UWP/tree/master

2. a RN 0.66 app with same nuget dependencies: https://github.com/jeanmaried/AdaptiveCard-RN

**Comment by chrisglein** [comment]
@jeanmaried Can you provide the callstack for this crash with symbols resolved?

**Comment by jeanmaried** [comment]
This is the only entry I see in VS Call Stack pane:

>	adaptivecardsample.exe!adaptivecardsample.App.InitializeComponent.AnonymousMethod__4_0(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) Line 53	C#

Not sure if this is what you mean. Seems to me like I properly resolved most of the symbols. Here is the Debub output:
```
'adaptivecardsample.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreRuntime.2.2_2.2.29713.2_x64__8wekyb3d8bbwe\System.Private.CoreLib.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\entrypoint\adaptivecardsample.exe'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\System.Runtime.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\WinMetadata\Windows.winmd'. Module was built without symbols.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\mscorlib.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Runtime.InteropServices.WindowsRuntime.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\Microsoft.ReactNative.winmd'. Module was built without symbols.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\Microsoft.UI.Xaml.Markup.winmd'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Threading.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Collections.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Reflection.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Threading.Tasks.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Runtime.WindowsRuntime.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Reflection.Extensions.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Linq.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\Microsoft.UI.Xaml.winmd'. Module was built without symbols.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Runtime.Extensions.dll'. Symbols loaded.
Exception thrown: 'System.IO.FileLoadException' in System.Private.CoreLib.dll
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\AdaptiveCards.dll'. 
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\Microsoft.ReactNative.Managed.dll'. 
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\Newtonsoft.Json.dll'. 
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Numerics.Vectors.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Runtime.WindowsRuntime.UI.Xaml.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Code\AdaptiveCardSample\windows\adaptivecardsample\bin\x64\Debug\AppX\AdaptiveCards.Rendering.Uwp.winmd'. Module was built without symbols.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Private.Uri.dll'. Symbols loaded.
The thread 0x164f8 has exited with code 0 (0x0).
The thread 0x10abc has exited with code 0 (0x0).
The thread 0x12828 has exited with code 0 (0x0).
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Diagnostics.Debug.dll'. Symbols loaded.
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Remote Debugger\x64\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. 
'adaptivecardsample.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\Program Files\WindowsApps\Microsoft.NET.CoreFramework.Debug.2.2_2.2.29301.2_x64__8wekyb3d8bbwe\System.Runtime.InteropServices.dll'. Symbols loaded.
```

**Comment by asklar** [comment]
here's the native stack trace:

```
>	KernelBase.dll!RaiseException()	Unknown
 	vcruntime140_app.dll!_CxxThrowException(void * pExceptionObject, const _s__ThrowInfo * pThrowInfo) Line 75	C++
 	Microsoft.ReactNative.dll!winrt::throw_hresult(const winrt::hresult result) Line 4892	C++
 	[Inline Frame] Microsoft.ReactNative.dll!winrt::check_hresult(const winrt::hresult) Line 4962	C++
 	[Inline Frame] Microsoft.ReactNative.dll!winrt::impl::consume_Windows_UI_Xaml_IDependencyObject<winrt::Windows::UI::Xaml::Documents::Inline>::GetValue(const winrt::Windows::UI::Xaml::DependencyProperty &) Line 868	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::TestHit(const winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::Xaml::Documents::Inline> & inlines, const winrt::Windows::Foundation::Point & pointerPos, bool & isHit) Line 616	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::TagFromOriginalSource(const winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs & args, __int64 * pTag, winrt::Windows::UI::Xaml::UIElement * pSourceElement) Line 579	C++
 	Microsoft.ReactNative.dll!Microsoft::ReactNative::TouchEventHandler::OnPointerMoved(const winrt::Windows::Foundation::IInspectable & __formal, const winrt::Windows::UI::Xaml::Input::PointerRoutedEventArgs & args) Line 159	C++
 	[Inline Frame] Microsoft.ReactNative.dll!winrt::Windows::UI::Xaml::Input::PointerEventHandler::<lambda_425c38b2fca626cb6c448a4a944c3950>::operator()(const winrt::Windows::Foundation::IInspectable &) Line 4182	C++
 	Microsoft.ReactNative.dll!winrt::impl::delegate<winrt::Windows::UI::Xaml::Input::PointerEventHandler,<lambda_425c38b2fca626cb6c448a4a944c3950>>::Invoke(void * sender, void * e) Line 1461	C++
```

I think its crashing in this code:
https://github.com/microsoft/react-native-windows/blob/0.66-stable/vnext/Microsoft.ReactNative/Views/TouchEventHandler.cpp#L609-L620
```cpp
if (const auto span = el.try_as<xaml::Documents::Span>()) {
      auto resTag = TestHit(span.Inlines().GetView(), pointerPos, isHit);

      if (resTag)
        return resTag;[Igor Klemenski, 2 years ago: • Fix - onPress callback not working for nested…](https://sourcegraph.com/github.com/microsoft/react-native-windows/-/commit/8fd8dcd3b4c6783ad176c620df57521c8131b894)

      if (isHit) {
        tag = el.GetValue(xaml::FrameworkElement::TagProperty()).try_as<winrt::IPropertyValue>();
        if (tag) {
          return tag;
        }
      }
```

RNW's input handler wrongly assumes that all of the UI elements in the tree will have been created by RNW; if the app is drawing XAML elements with other frameworks (XAML directly, or AC) then this assumption is incorrect.

**Comment by rozele** [comment]
I think this is probably fixed in 0.67 with the new approach to text hit testing. To find the first React view in the hierarchy, it uses ReadLocalValue, rather than GetValue, which is probably less crash prone.

**Comment by jeanmaried** [comment]
@rozele I just tested with 0.67 and the issue persists.

**Comment by asklar** [comment]
Yes the issue persists. The problem is not only that RNW assumes there is a tag, but also that AC also uses Tag, but not as an int. So an element created by AC will have a Tag property that is a WinRT object. RNW detects that a tag is set, and then blindly tries to get an int from it. In the case of the AC element, there is no int, there's a WinRT object (of type `AdaptiveCards.Rendering.Uwp."ElementTagContent"`.
The fix is for RNW to not assume that tags are set by RNW only. Since we use `int64` for tag everywhere, that's going to be a somewhat invasive change. For the time being, I'll just add some surgical checks for "is it an int" and assume that if it is, it was set by RNW. Still not a perfect solution but should fix the crash.

**Comment by chrisglein** [comment]
Related? #4187

**Comment by jeanmaried** [comment]
@asklar thanks for the fast turnaround!
